# Generated by Django 3.1.1 on 2020-12-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customadmin', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.userinformation'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.language'),
        ),
        migrations.AddField(
            model_name='personinroom',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.chatactivity'),
        ),
        migrations.AddField(
            model_name='personinroom',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses'),
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.language'),
        ),
        migrations.AddField(
            model_name='fileactivity',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.activitycategory'),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_user_categories', to='customadmin.usercategories'),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='rejected',
            field=models.ManyToManyField(related_name='end_user_course_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='requests',
            field=models.ManyToManyField(related_name='end_user_course_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='students',
            field=models.ManyToManyField(related_name='end_user_course_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_categories', to='customadmin.categories'),
        ),
        migrations.AddField(
            model_name='courses',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_courses', to='customadmin.organization'),
        ),
        migrations.AddField(
            model_name='courses',
            name='rejected',
            field=models.ManyToManyField(related_name='rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='requests',
            field=models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.userinformation'),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses'),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentvideo',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_content', to='customadmin.subtopic'),
        ),
        migrations.AddField(
            model_name='contentvideo',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content', to='customadmin.topic'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sessionactivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.sessionactivity'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatactivity',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.activitycategory'),
        ),
        migrations.AddField(
            model_name='categorieshirerchy',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.categories'),
        ),
        migrations.AddField(
            model_name='categorieshirerchy',
            name='category_father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_father', to='customadmin.categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.question'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_topic', to='customadmin.topic'),
        ),
        migrations.AddField(
            model_name='activityadding',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses'),
        ),
        migrations.AddField(
            model_name='activityadding',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='spinactivityenroll',
            unique_together={('candidate', 'spinactivity')},
        ),
    ]
