# Generated by Django 3.1.1 on 2020-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_auto_20201203_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategories',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
