# Generated by Django 3.1.1 on 2020-12-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_usercategories_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_topic', to='customadmin.coursesenduser'),
        ),
    ]
