# Generated by Django 3.1.1 on 2020-12-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_auto_20201207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
    ]
