# Generated by Django 3.1.1 on 2020-12-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_auto_20201208_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentvideo',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='contentvideo',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser'),
        ),
        migrations.AddField(
            model_name='contentvideo',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
    ]
