# Generated by Django 3.1.1 on 2020-12-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_auto_20201209_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenduser',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
