# Generated by Django 3.1.1 on 2020-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_auto_20201215_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='contact_person_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='phone',
            new_name='contact_person_phone',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='organization_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_person_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sector_type',
            field=models.CharField(choices=[('GOVERNMENT', 'government'), ('CORPORATE', 'corporate')], default='GOVERNMENT', max_length=125),
        ),
        migrations.AddField(
            model_name='organization',
            name='unique_code',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
