# Generated by Django 3.1.1 on 2020-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_auto_20201215_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='certificate',
            field=models.TextField(null=True),
        ),
    ]
