# Generated by Django 3.1.1 on 2020-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_organization_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenduser',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('STUDENTS_ONLY', 'Students only'), ('COLLABORATORS_ONLY', 'Collaborators only'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='Whether the course should remain private (for you only), restricted to your collaborators, your students or public', max_length=20, verbose_name='Access'),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='registration_enabled',
            field=models.BooleanField(default=False, help_text='Whether users are authorised to register or unregister from this course', verbose_name='Registration enabled'),
        ),
        migrations.AddField(
            model_name='coursesenduser',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Whether the course should be considered as a draft, published or archived. Archived means read-only.', max_length=20, verbose_name='State'),
        ),
    ]
