# Generated by Django 3.1.1 on 2021-01-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0017_auto_20210105_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenroll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser'),
        ),
    ]
