# Generated by Django 3.1.1 on 2021-01-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0018_auto_20210105_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities'),
        ),
    ]
