# Generated by Django 3.1.1 on 2021-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_courseenroll_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='about',
            field=models.CharField(default=None, help_text='in minutes', max_length=255),
        ),
    ]
