# Generated by Django 3.1.1 on 2021-01-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0020_auto_20210106_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='course',
            field=models.ManyToManyField(to='customadmin.CoursesEndUser'),
        ),
    ]
