# Generated by Django 3.1.1 on 2021-01-10 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0021_organization_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
