# Generated by Django 3.1.1 on 2021-01-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0022_organization_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='content_id',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
