# Generated by Django 3.1.1 on 2021-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_activities_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='content_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
