# Generated by Django 3.1.1 on 2021-01-13 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0024_auto_20210112_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenroll',
            unique_together={('user', 'course')},
        ),
    ]
