# Generated by Django 3.1.1 on 2021-01-13 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0025_auto_20210113_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenroll',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='topic',
        ),
        migrations.CreateModel(
            name='TopicWiseAnswerpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
