# Generated by Django 3.1.1 on 2021-01-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0026_auto_20210113_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicwiseanswerpaper',
            unique_together={('course', 'topic')},
        ),
    ]
