# Generated by Django 3.1.1 on 2021-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0027_auto_20210113_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenroll',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseenroll',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='one time enroll for user'),
        ),
    ]
