# Generated by Django 3.1.1 on 2021-01-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0028_auto_20210113_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicwiseanswerpaper',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities'),
        ),
    ]
