# Generated by Django 3.1.1 on 2021-01-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0029_auto_20210113_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicwiseanswerpaper',
            unique_together={('topic', 'activity')},
        ),
    ]
