# Generated by Django 3.1.1 on 2021-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0031_auto_20210113_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='activity_completion',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='is_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
