# Generated by Django 3.1.1 on 2021-01-13 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0032_auto_20210113_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicWiseAnswerpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('content_video_length', models.CharField(max_length=123)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='activity_completion',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='topic',
        ),
        migrations.AddConstraint(
            model_name='courseenroll',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='one time enroll for user'),
        ),
        migrations.AddField(
            model_name='topicwiseanswerpaper',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities'),
        ),
        migrations.AddField(
            model_name='topicwiseanswerpaper',
            name='content_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.contentvideo'),
        ),
        migrations.AddField(
            model_name='topicwiseanswerpaper',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser'),
        ),
        migrations.AddField(
            model_name='topicwiseanswerpaper',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic'),
        ),
        migrations.AddField(
            model_name='topicwiseanswerpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topicwiseanswerpaper',
            unique_together={('topic', 'content_video'), ('topic', 'activity')},
        ),
    ]
