# Generated by Django 3.1.1 on 2021-01-14 05:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0033_auto_20210113_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicwiseanswerpaper',
            unique_together={('user', 'activity'), ('user', 'content_video')},
        ),
    ]
