# Generated by Django 3.1.1 on 2021-01-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0034_auto_20210114_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinactivityanswer',
            name='spinactivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.spinactivity'),
        ),
    ]
