# Generated by Django 3.1.1 on 2021-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0037_auto_20210120_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentvideo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='course_video_thumbnail'),
        ),
    ]
