# Generated by Django 3.1.1 on 2021-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0039_auto_20210120_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='organization_logo/'),
        ),
    ]
