# Generated by Django 3.1 on 2021-01-22 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0040_auto_20210121_1746'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseenroll',
            name='one time enroll for user',
        ),
        migrations.AlterUniqueTogether(
            name='courseenroll',
            unique_together={('user', 'course')},
        ),
    ]
