# Generated by Django 3.1 on 2021-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0042_auto_20210122_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo1',
            field=models.ImageField(null=True, upload_to='organization_logo/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_second_logo',
            field=models.BooleanField(default=False),
        ),
    ]
