# Generated by Django 3.1 on 2021-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0043_auto_20210125_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='end_date',
            field=models.DateField(blank=True, help_text='m/d/y format', null=True),
        ),
    ]
