# Generated by Django 3.1 on 2021-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0044_auto_20210125_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='end_date',
            field=models.CharField(blank=True, help_text='m/d/y format', max_length=125, null=True),
        ),
    ]
