# Generated by Django 3.1.1 on 2021-02-03 08:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('customadmin', '0050_assignmentactivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenduser',
            name='course_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
