# Generated by Django 3.1.1 on 2021-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0053_auto_20210203_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentanswer',
            name='submission',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
