# Generated by Django 3.1.1 on 2021-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0054_assignmentanswer_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenduser',
            name='course_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursesenduser',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
