# Generated by Django 3.1.1 on 2021-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0055_auto_20210203_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentvideo',
            name='duration',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('mcq', 'mcq'), ('spin activity', 'spin activity'), ('Assignment', 'Assignment')], max_length=50),
        ),
    ]
