# Generated by Django 3.1.1 on 2021-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0056_auto_20210208_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('quiz', 'quiz'), ('spin_activity', 'spin_activity'), ('Assignment', 'Assignment'), ('Drag and Drop', 'Drag and Drop'), ('mcq', 'mcq')], max_length=50),
        ),
    ]
