# Generated by Django 3.1.1 on 2021-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0057_auto_20210208_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
