# Generated by Django 3.1.1 on 2021-02-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0059_auto_20210212_1015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'course')},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='thumbnail',
        ),
    ]
