# Generated by Django 3.1.1 on 2021-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0060_auto_20210215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
