# Generated by Django 3.1.1 on 2021-02-16 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0061_auto_20210215_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenduser',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('STUDENTS_ONLY', 'Students only')], default='PUBLIC', help_text='Whether the course should remain private (for you only), restricted to your collaborators, your students or public', max_length=20, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='coursesenduser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_user_categories', to='customadmin.usercategories'),
        ),
        migrations.AlterField(
            model_name='coursesenduser',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Whether the course should be considered as a draft, published or archived. Archived means read-only.', max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
