# Generated by Django 3.1.1 on 2021-02-17 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0062_auto_20210216_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragDropActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=300)),
                ('settings_data', models.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd', to='customadmin.activities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='coursesenduser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_user_categories', to='customadmin.usercategories'),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DragDropActivityElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('label', models.CharField(max_length=300)),
                ('settings_data', models.JSONField()),
                ('dd_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd_element', to='customadmin.dragdropactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DragDropActivityAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('answer_data', models.JSONField()),
                ('grade', models.CharField(max_length=100)),
                ('dd_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.dragdropactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
