# Generated by Django 3.1.1 on 2021-02-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0063_auto_20210218_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenduser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_user_categories', to='customadmin.usercategories'),
        ),
    ]
