# Generated by Django 3.1.1 on 2021-02-18 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0066_remove_usercategories_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='categories_file'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
