# Generated by Django 3.1.1 on 2021-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0068_auto_20210218_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenduser',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('STUDENTS_ONLY', 'Students only')], default='PUBLIC', help_text='Whether the course should be for your students or public .', max_length=20, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='coursesenduser',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Whether the course should be considered as a draft, published .', max_length=20, verbose_name='State'),
        ),
    ]
