# Generated by Django 3.1.1 on 2021-02-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0071_auto_20210221_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinactivity',
            name='question_in_seq',
            field=models.BooleanField(default=False),
        ),
    ]
