# Generated by Django 3.1.1 on 2021-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0072_spinactivity_question_in_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
