# Generated by Django 3.1.1 on 2021-02-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0073_auto_20210223_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='end_date',
        ),
    ]
