# Generated by Django 3.1.1 on 2021-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0074_remove_topic_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
