# Generated by Django 3.1.1 on 2021-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0076_auto_20210223_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
