# Generated by Django 3.1.1 on 2021-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0078_auto_20210223_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinactivity',
            name='question_in_seq',
        ),
        migrations.AlterField(
            model_name='topic',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
