# Generated by Django 3.1.1 on 2021-03-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20210225_1111'),
        ('customadmin', '0080_auto_20210302_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactivity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_session', to='customadmin.coursesenduser'),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_session', to='customadmin.organization'),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.userinformation'),
        ),
    ]
