# Generated by Django 3.1.1 on 2021-04-01 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0081_auto_20210302_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicwiseanswerpaper',
            unique_together={('user', 'activity')},
        ),
    ]
