# Generated by Django 3.1.1 on 2021-04-03 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0082_auto_20210401_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='students',
            field=models.ManyToManyField(related_name='organization_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
