# Generated by Django 3.1.1 on 2021-04-20 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0084_auto_20210412_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactivity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
