# Generated by Django 3.2.4 on 2021-07-15 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0085_auto_20210420_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentactivity',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignmentactivity',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
