# Generated by Django 3.2.4 on 2021-07-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0086_auto_20210715_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=125)),
                ('img', models.ImageField(upload_to='urlactivityimage/')),
                ('website', models.URLField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
            ],
        ),
    ]
