# Generated by Django 3.2.4 on 2021-07-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0087_urlactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlactivity',
            name='activity',
        ),
    ]
