# Generated by Django 3.2.4 on 2021-07-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0088_remove_urlactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlactivity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities'),
        ),
    ]
