# Generated by Django 3.2.4 on 2021-07-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0089_urlactivity_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPTActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('pptfile', models.FileField(upload_to='pptactivity/')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
            ],
        ),
        migrations.CreateModel(
            name='PDFActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('pdfFile', models.FileField(upload_to='pdfactivity/')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
            ],
        ),
        migrations.CreateModel(
            name='DocActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('docfile', models.FileField(upload_to='docfile/')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
            ],
        ),
    ]
