# Generated by Django 3.2.5 on 2021-07-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0090_docactivity_pdfactivity_pptactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfactivity',
            old_name='pdfFile',
            new_name='pdffile',
        ),
    ]
