# Generated by Django 3.2.5 on 2021-07-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0091_rename_pdffile_pdfactivity_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('pdffile', models.FileField(upload_to='pdfactivity/')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.activities')),
            ],
        ),
    ]
