# Generated by Django 3.2.6 on 2021-08-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0093_usergrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityAdding',
        ),
    ]
