# Generated by Django 3.2.6 on 2021-08-17 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0094_delete_activityadding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAdding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
