# Generated by Django 3.2.6 on 2021-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0097_delete_groupp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('u_id', models.CharField(max_length=125)),
                ('org', models.CharField(max_length=124)),
                ('users', models.CharField(max_length=124)),
                ('permissions', models.CharField(max_length=123)),
            ],
        ),
    ]
