# Generated by Django 3.2.6 on 2021-08-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0098_groupp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupp',
        ),
        migrations.AddField(
            model_name='assignmentanswer',
            name='grade',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
