# Generated by Django 3.2.6 on 2021-09-07 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0099_auto_20210827_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenduser',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
