# Generated by Django 3.2.6 on 2021-09-07 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0100_coursesenduser_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactivity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
