# Generated by Django 3.2.6 on 2021-09-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0101_alter_sessionactivity_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentactivity',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
