# Generated by Django 3.2.6 on 2021-09-21 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0102_assignmentactivity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=10, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_candidates', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='organization_logo/')),
                ('logo1', models.ImageField(null=True, upload_to='organization_logo/')),
                ('show_second_logo', models.BooleanField(default=False)),
                ('contact_person_name', models.CharField(max_length=225, null=True)),
                ('contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('contact_person_phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('sector_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='government', max_length=125)),
                ('certificate', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.state')),
            ],
        ),
    ]
