# Generated by Django 3.2.6 on 2021-09-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0103_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(upload_to='college_logo/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo1',
            field=models.ImageField(null=True, upload_to='college_logo/'),
        ),
    ]
