# Generated by Django 3.1.1 on 2021-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='pincode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='registration_date',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
