# Generated by Django 3.1.1 on 2021-01-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_userinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='houseno',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
