# Generated by Django 3.1.1 on 2021-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_userinformation_houseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(null=True, upload_to='user_profile/'),
        ),
    ]
