# Generated by Django 3.1 on 2021-01-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210121_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='registration_date',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
