# Generated by Django 3.1.1 on 2021-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20210125_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='address1',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
