# Generated by Django 3.2.4 on 2021-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20210225_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
