# Generated by Django 3.2.4 on 2021-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_userinformation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
