# Generated by Django 3.2.4 on 2021-07-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0085_auto_20210420_1109'),
        ('organization', '0012_alter_userinformation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.city'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.country'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.state'),
        ),
    ]
