# Generated by Django 3.2.4 on 2021-07-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20210701_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='state',
        ),
    ]
