# Generated by Django 3.1.1 on 2021-02-25 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customadmin', '0079_auto_20210225_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SlugField(max_length=225, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('started', 1), ('ended', 2), ('will start', 3)], max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser')),
            ],
        ),
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatmessage', models.TextField()),
                ('chattime', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser')),
                ('userfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_userfrom', to=settings.AUTH_USER_MODEL)),
                ('userto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_userto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SlugField(max_length=225)),
                ('channel_name', models.CharField(max_length=225, unique=True)),
                ('user_id', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser')),
            ],
            options={
                'unique_together': {('course', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=40)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser')),
            ],
            options={
                'unique_together': {('course', 'user_name')},
            },
        ),
    ]
