# Generated by Django 3.1.1 on 2020-10-19 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0002_courses_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('chat', 'chat'), ('pdf', 'pdf'), ('question', 'question')], max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfactivity_topic', to='customadmin.topic')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='pdfactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='pdfactivity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pdfactivity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pdfactivity',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='questionactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='questionactivity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionactivity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionactivity',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionactivity',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AcitivityCategory',
        ),
        migrations.DeleteModel(
            name='PdfActivity',
        ),
        migrations.DeleteModel(
            name='QuestionActivity',
        ),
    ]
