# Generated by Django 3.1.1 on 2020-10-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_auto_20201020_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_topic', to='customadmin.topic'),
        ),
    ]
