# Generated by Django 3.1.1 on 2020-10-20 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0005_auto_20201020_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user', models.CharField(max_length=225)),
                ('room', models.CharField(max_length=225, unique=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=225)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.chatactivity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
