# Generated by Django 3.1.1 on 2020-10-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_auto_20201026_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionactivity',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.courses'),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='topic',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
