# Generated by Django 3.1.1 on 2020-10-27 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_auto_20201026_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactivity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
