# Generated by Django 3.1.1 on 2020-10-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_auto_20201027_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='display_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='mute_participant_upon_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='record_session_visibility_to_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_session', to='customadmin.courses'),
        ),
    ]
