# Generated by Django 3.1.1 on 2020-10-28 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_auto_20201027_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenroll',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='start_date',
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
