# Generated by Django 3.1.1 on 2020-11-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0018_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='session_room_id',
            field=models.CharField(max_length=125, null=True, unique=True),
        ),
    ]
