# Generated by Django 3.1.1 on 2020-11-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_sessionactivity_session_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='room_id',
        ),
    ]
