# Generated by Django 3.1.1 on 2020-11-02 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0020_remove_classroom_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('video', models.FileField(upload_to='course_video/')),
                ('description', models.CharField(max_length=225)),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.subtopic')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
