# Generated by Django 3.1.1 on 2020-11-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0021_contentvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_content', to='customadmin.subtopic'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content', to='customadmin.topic'),
        ),
    ]
