# Generated by Django 3.1.1 on 2020-11-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0022_auto_20201102_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subtopic', to='customadmin.topic'),
        ),
    ]
