# Generated by Django 3.1.1 on 2020-11-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0024_auto_20201103_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='name',
        ),
    ]
