# Generated by Django 3.1.1 on 2020-11-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0026_auto_20201104_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.organization'),
        ),
    ]
