# Generated by Django 3.1.1 on 2020-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0027_categories_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
    ]
