# Generated by Django 3.1.1 on 2020-11-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0028_categories_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('category', 'category'), ('subcategory', 'subcategory')], default='category', max_length=25),
        ),
        migrations.AlterField(
            model_name='categorieshirerchy',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.categories'),
        ),
    ]
