# Generated by Django 3.1.1 on 2020-11-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0030_topicrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('topic', 'topic'), ('subtopic', 'subtopic')], default='topic', max_length=10),
        ),
    ]
