# Generated by Django 3.1.1 on 2021-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_organization',
            field=models.BooleanField(default=False),
        ),
    ]
