# Generated by Django 3.2.4 on 2021-06-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210423_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverify',
            name='email',
            field=models.CharField(max_length=125, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accountverify',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountverify',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
