# Generated by Django 3.1.1 on 2020-12-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preassesment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('upload', 'Assignment Upload'), ('arrange', 'Arrange in Correct Order')], default='mcq', max_length=24),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=20, verbose_name='Duration of quiz in minutes')),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=256)),
                ('pass_criteria', models.FloatField(default=40, verbose_name='Passing percentage')),
                ('attempts_allowed', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (-1, 'Infinite')], default=1)),
                ('time_between_attempts', models.FloatField(default=0.0, verbose_name='Time Between Quiz Attempts in hours')),
                ('is_trial', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, default=None, null=True, verbose_name='Instructions for Students')),
                ('view_answerpaper', models.BooleanField(default=False, verbose_name='Allow student to view their answer\t\t\t\t\t\t\t\t\t\t\tpaper')),
                ('allow_skip', models.BooleanField(default=True, verbose_name='Allow students to skip questions')),
                ('weightage', models.FloatField(default=100, help_text='Will be considered as percentage')),
                ('is_exercise', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
