# Generated by Django 3.1.1 on 2021-01-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0002_auto_20201221_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='shuffle_testcases',
        ),
    ]
