# Generated by Django 3.1.1 on 2021-01-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0003_remove_questionpaper_shuffle_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preassesment.quiz'),
        ),
    ]
