# Generated by Django 3.1.1 on 2021-01-12 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0022_organization_students'),
        ('preassesment', '0004_auto_20210112_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coursesenduser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start Date and Time of the quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.topic'),
        ),
    ]
