# Generated by Django 3.1.1 on 2021-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0005_auto_20210112_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='summary',
            new_name='question_name',
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
