# Generated by Django 3.1 on 2021-01-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0006_auto_20210118_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='start_date_time',
        ),
    ]
