# Generated by Django 3.1 on 2021-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0008_auto_20210127_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade_assignment_upload',
        ),
        migrations.RemoveField(
            model_name='question',
            name='partial_grading',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices')], default='mcq', max_length=24),
        ),
    ]
