# Generated by Django 3.1.1 on 2021-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0009_auto_20210127_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='weightage',
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(None, 'Select Question Type'), ('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices')], default=None, max_length=24),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_between_attempts',
            field=models.FloatField(default=0.0, verbose_name='Time Between Quiz Attempts in minutes'),
        ),
    ]
