# Generated by Django 3.2.4 on 2021-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0011_auto_20210705_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_between_attempts',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Time Between Quiz Attempts in minutes'),
        ),
    ]
