# Generated by Django 3.2.4 on 2021-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0012_alter_quiz_time_between_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_between_attempts',
            field=models.FloatField(default=0.0, null=True, verbose_name='Time Between Quiz Attempts in minutes'),
        ),
    ]
