# Generated by Django 3.2.4 on 2021-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0013_alter_quiz_time_between_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_e',
        ),
    ]
