# Generated by Django 3.2.4 on 2021-07-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0014_auto_20210706_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='solution',
            new_name='explanation',
        ),
    ]
