# Generated by Django 3.2.4 on 2021-07-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0015_rename_solution_question_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_name',
        ),
    ]
