# Generated by Django 3.2.4 on 2021-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0016_auto_20210707_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
