# Generated by Django 3.2.4 on 2021-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0017_question_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='option_c',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='option_d',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='option_e',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
