# Generated by Django 3.2.4 on 2021-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0018_auto_20210707_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option_a',
            field=models.CharField(default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_b',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_c',
            field=models.CharField(default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_d',
            field=models.CharField(default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_e',
            field=models.CharField(default=None, max_length=125, null=True),
        ),
    ]
