# Generated by Django 3.2.4 on 2021-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0019_auto_20210707_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option_e',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
