# Generated by Django 3.2.6 on 2021-10-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(default=1, upload_to='blog_image/'),
            preserve_default=False,
        ),
    ]
