# Generated by Django 3.2.6 on 2021-10-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211025_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='blog_image/'),
        ),
    ]
