# Generated by Django 3.1.1 on 2021-02-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
